---
python_transforms:
  - name: device_transform
    class_name: DeviceTransform
    file_path: "device_transform.py"

queries:
  - name: device_query
    file_path: "device_query.gql"
  - name: all_devices_query
    file_path: "all_devices_query.gql"
