---
python_transforms:
  - name: device_transform_yaml
    class_name: DeviceTransformYaml
    file_path: "transforms/device_transform.py"

queries:
  - name: device_query
    file_path: "queries/device_query.gql"
  - name: all_devices_query
    file_path: "queries/all_devices_query.gql"

artifact_definitions:
  - name: "device_config_yaml"
    artifact_name: "Device config YAML"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "all_devices"
    transformation: "device_transform_yaml"
