---
python_transforms:
  - name: devices_transform
    class_name: DevicesTransform
    file_path: "devices_transform.py"

queries:
  - name: devices_query
    file_path: "devices_query.gql"
  - name: all_devices_query
    file_path: "all_devices_query.gql"
