srl_nokia-interfaces:interface:
- name: ethernet-1/1
  description: spine1:et-1/1.0
- name: ethernet-1/2
  description: spine2:et-1/1.0
- name: system0
  subinterface:
  - index: 0
    ipv4:
      address:
      - ip-prefix: 172.16.0.11/32
    ipv6:
      address:
      - ip-prefix: fd::11/128
srl_nokia-network-instance:network-instance:
- name: default
  protocols:
    srl_nokia-bgp:bgp:
      router-id: 172.16.0.11
      neighbor:
      - peer-address: fd::1
        admin-state: enable
        peer-group: IBGP-OVERLAY
      - peer-address: fd::2
        admin-state: enable
        peer-group: IBGP-OVERLAY

