query InterfaceDeviceQuery($interface_id: [ID]) {
  InfraInterfaceL3(ids: $interface_id) {
    edges {
      node {
        id
        name {
          value
        }
        device {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}
