query InterfaceDeviceQuery($interface: String!) {
  InfraInterface(name__value: $interface) {
    edges {
      node {
        device {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}
